# Generated by Django 3.2.4 on 2021-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211215_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='portfolio')),
                ('slider1', models.ImageField(blank=True, upload_to='portfolio')),
                ('slider2', models.ImageField(blank=True, upload_to='portfolio')),
                ('slider3', models.ImageField(blank=True, upload_to='portfolio')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('project_url', models.CharField(blank=True, max_length=100)),
                ('project_date', models.DateField()),
            ],
        ),
    ]
